parameters:
    acl_service.class:       Flash\Bundle\DefaultBundle\Services\ACLService
    acl_manager.class:       Flash\Bundle\DefaultBundle\Services\ACLManager
    user_event.class:        Flash\Bundle\DefaultBundle\Services\UserEventFactory
    request_injector.class:  Flash\Bundle\DefaultBundle\Services\RequestInjector
    common_service.class:    Flash\Bundle\DefaultBundle\Services\CommonService
    
    
    event_service.class:     Flash\Bundle\DefaultBundle\Services\Entity\EventService
    account_service.class:   Flash\Bundle\DefaultBundle\Services\Entity\AccountService
    group_service.class:     Flash\Bundle\DefaultBundle\Services\Entity\GroupService
    photo_service.class:     Flash\Bundle\DefaultBundle\Services\Entity\PhotoService
    comment_service.class:   Flash\Bundle\DefaultBundle\Services\Entity\CommentService
    
        
services:
  
    request_injector:
        class:        %request_injector.class%
        public:       false
        arguments:    ['@service_container']
  
    common_service:
        abstract:     true
        class:         %common_service.class%
        arguments:    ["@security.context", "@request_injector"]        
        
    user_event_service:
        class:        %user_event.class%
        parent:       common_service
        
    event_service:
        class:        %event_service.class%
        parent:       common_service
        
    account_service:
        class:        %account_service.class%
        parent:       common_service
        
    group_service:
        class:        %group_service.class%
        parent:       common_service
        
    photo_service:
        class:        %photo_service.class%
        parent:       common_service
        
    comment_service:
        class:        %comment_service.class%
        parent:       common_service
        
    user_event:
        class:        %user_event.class%
        arguments:    ['@security.context']
        
    acl_service:
        class:        %acl_service.class%
        arguments:    ['@security.context', '@security.acl.provider']
        
    acl_manager:
        class:        %acl_manager.class%
        arguments:    ['@security.acl.provider', '@security.context']
        

