jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Flash\Bundle\DefaultBundle\Entity\Account:
            algorithm:         sha1
            encode_as_base64: false
            iterations:        1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_CUSTOMER:    ROLE_USER
        ROLE_PARTICIPANT: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        administrators:
            entity: { class: Flash\Bundle\DefaultBundle\Entity\Account, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _flash_login
                default_target_path: /main
                always_use_default_target_path: true
            logout:
                path:   _flash_logout
                target: _demo

    access_control:
#         - { path: ^/rest, roles: [ ROLE_USER ] }
         #- { path: ^/demo, roles: [ ROLE_ADMIN, ROLE_USER ] }
#         - { path: ^/admin/, role: ROLE_ADMIN }
#         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
