acme_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

acme_test_user_all:
    pattern:  /users
    defaults: { _controller: AcmeTestBundle:Default:all, _format: ~ }
    requirements:
        _method: GET
        
        
acme_demo_user_get:
    pattern:  /users/{id}
    defaults: { _controller: AcmeDemoBundle:User:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"
        
acme_demo_user_get:
    pattern:  /serial
    defaults: { _controller: AcmeTestBundle:Default:serialized, _format: ~ }
    requirements:
        _method: GET
        
#group:
#    type: rest
#    resource: Acme\TestBundle\Controller\GroupController
#
#account:
#    type: rest
#    parent: group
#    resource: Acme\TestBundle\Controller\AccountController